---
# tasks file for apache2-roles

- name: Install apache2
  apt: 
   name: apache2
   state: present

- name: Start apache2 service
  service: 
   name: apache2
   state: started

- name: Create Apache2 virtualhost config file
  template:
    src: virtualhost.conf.j2
    dest: /etc/apache2/sites-available/{{ domain_name }}.conf
  notify:
     - enable apache2 virtualhost

- name: Disable default apache2 virtualhost
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify: restart apache2

- name: Enable new virtualhost
  copy:
    src: /etc/ansible/apache2-roles/templates/virtualhost.conf.j2
    dest: /etc/apache2/sites-enabled/{{ domain_name }}.conf
    mode: '0644'
  notify: restart apache2

